name = "ForecastData"
uuid = "97bfbf95-b26f-4f60-9525-b5a468fedbf5"
authors = ["Fran Urbano <viraltux@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
